const dictionary = {
    "Tópicos": "Topics",
    "Introdução": "Introduction",
    "Minha História": "My Story",
    "Carreira": "Career",
    "Desenvolvimento de Jogos": "Game Development",
    "Ilustração Digital": "Digital Illustration",
    "Desenvolvimento Web": "Web Development",
    "Marketing": "Marketing",
    "Ciências da Computação": "Computer Science",
    "Atualmente": "Currently",
    "Minhas Qualidades": "My Qualities",
    "Certificados e Contatos": "Certificates and Contacts",

    "EN-US": "EN-US",
    "PT-BR": "PT-BR",

    "Olá, meu nome é Vinícius Torres (silence please), 19 anos, com nacionalidade brasileira e europeia, atualmente morando no Brasil, Pernambuco. Esse projeto é um resumo de toda a minha jornada de estudos e projetos com ciencias da computação, artes, marketing e outros.": "Hello, my name is Vinícius Torres (silence please), 19 years old, with Brazilian and European nationality, currently living in Brazil, Pernambuco. This project is a summary of my entire journey of studies and projects with computer science.",
    "Meu objetivo com esse portifólio é proporcionar um olhar mais humano em quem eu sou, minha história, personalidade, e também mostrar todos os projetos que fiz até agora.": "My goal with this portfolio is to provide a more human look at who I am, my story, personality, and also to show all the projects I've done so far.",

    "Logo na minha adolescência, comecei a me questionar sobre o que significa independência, quem eu sou e qual o sentido da vida. Aos 15 anos, comecei a morar sozinho com ajuda financeira dos meus pais e, assim, pude passar mais tempo com meus pensamentos, desenvolvendo minha autonomia." : "Right in my teens, I began to question myself what independence means, who I am and what is the meaning of life. At 15, I started living alone with my parents' financial help, so I could spend more time with my thoughts, developing my autonomy.",
    "Durante esse período vivendo sozinho, pude dedicar meu tempo à minha paixão pela filosofia, o que contribuiu para o desenvolvimento da minha personalidade mais reflexiva e crítica." : "During this period living alone, I was able to devote my time to my passion for philosophy, which contributed to the development of my most reflective and critical personality.",
    "Aos 18 anos, recebi uma pequena quantia de dinheiro que me permitiu sair da casa dos meus pais, e usei-a para buscar novas oportunidades em Florianópolis." : "At 18, I received a small amount of money that allowed me to leave my parents' house, and I used it to look for new opportunities in Florianópolis.",
    "Foi a partir desse momento que comecei a pensar mais seriamente sobre o meu futuro e a me questionar sobre a minha escolha de carreira e como ganhar dinheiro.": "It was from that moment on that I started to think more seriously about my future and to question myself about my career choice and how to earn money.",
    "Durante o meu tempo em Florianópolis, por estar próximo da Universidade Federal, tive a oportunidade de conhecer diversos estudantes, incluindo alguns da área de filosofia. Essa época foi uma das mais enriquecedoras da minha vida, pois aprendi muito sobre relacionamentos, socialização, sociedade e política. Aprendi também que às vezes devemos priorizar os sentimentos dos outros ao invés de priorizarmos estarmos sempre certos. É extremamente importante pensar nas emoções e sentimentos dos outros, mas ao mesmo tempo, não esquecermos dos nossos.": "During my time in Florianópolis, being close to the Federal University, I had the opportunity to meet several students, including some from the field of philosophy. That time was one of the most enriching of my life, as I learned a lot about relationships, socialization, society and politics. I also learned that sometimes we should prioritize the feelings of others instead of prioritizing always being right. It is extremely important to think about the emotions and feelings of others, but at the same time, not to forget our own.",

    "Sozinho aos 17 anos, em uma cidade desconhecida, sem amigos ou família e sem estar matriculado em uma universidade, tive que tomar uma decisão: como me sustentar no futuro?": "Alone at 17, in an city that I never visited before, without friends or family and without being enrolled in a university, I had to make a decision: how to support myself financially in the future?",

    "Minha primeira escolha foi aprender desenvolvimento de jogos de forma auto didata. Assistindo tutoriais gratuitos e praticando com exercícios, aprendi o básico de C# e estava pronto para colocar meus conhecimentos em prática. Com alguns protótipos já criados, me senti confiante para participar de uma game jam. Na época, LudWig estava organizando uma com o tema \"Foddian Games\" (jogos frustrantes de jogar, como Jump King).": "My first choice was to learn game development in a self-taught way. Watching free tutorials and practicing with exercises, I learned the basics of C# and was ready to put my knowledge into practice. With some prototypes already created, I felt confident to participate in a game jam. At the time, LudWig was hosting one themed around \"Foddian Games\" (frustrating games to play, like Jump King).",
    "Usando o Unity, em menos de uma semana, fiz um jogo rogue like chamado Coliseum, intencionalmente difícil.": "Using Unity, in less than a week, I made an intentionally difficult rogue like game called Coliseum.",
    "Disponível no itch.io": "Available on itch.io",
    "Com esse projeto, aprendi a lidar com prazos apertados, a aprender ferramentas com base no que é necessário, a considerar o tempo e as limitações de produção e a questionar se a velocidade é mais importante. Em seguida, criei um código que atendesse a essa demanda e, se fosse necessário escalar o projeto, refatoraria o código a partir dessa demanda. Aprendi também que a pré-otimização e a pré-refatoração podem ser obstáculos que impedem a criatividade e dificultam a adição de mecânicas para um rápido teste.": "With this project, I learned to deal with tight deadlines, to learn tools based on what is needed, to consider time and production limitations, and to question whether speed is more important. Then I created code that met that demand, and if the project needed to scale, I would refactor the code around that demand. I also learned that pre-optimization and pre-refactoring can be hurdles that impede creativity and make it difficult to add mechanics for quick testing.",
    "Ter mergulhado no desenvolvimento de jogos me proporcionou grandes experiências, como entender as causas que levam equipes a não conseguirem finalizar um projeto para game jam, compreender as limitações individuais e aprimorar minhas habilidades de relacionamento com equipes e projetos online. Todos os grupos em que participei se comunicavam em inglês, o que me ajudou a aperfeiçoar minhas habilidades de comunicação nessa língua.": "Having immersed myself in game development provided me with great experiences, such as understanding the causes that lead teams to not being able to finalize a project for game jam, understanding individual limitations and improving my skills in relationship with teams and online projects. All the groups I participated in communicated in English, which helped me to improve my communication skills in that language.",
    "Com isso, surgiu outra game jam e conheci um cara super legal com quem decidi criar um jogo cujo objetivo era simplesmente relaxar, sem objetivos, pressão ou punição por perder ou game over, chamado Farmlax. Foi uma experiência pura de apenas desfrutar um jogo, e só. O jogo foi feito em dois dias durante o fim de semana, já que ele trabalhava e era o único tempo livre que tínhamos. Foi extremamente divertido criar um jogo tão rápido, tão simples e que conseguia transmitir uma sensação usando apenas o necessário. Aprendi muito sobre lidar com o perfeccionismo e criar protótipos rapidamente.": "With that, another game jam came up and I met a super nice guy with whom I decided to create a game whose goal was simply to relax, without goals, pressure or punishment for losing or game over, called Farmlax. It was a pure experience of just enjoying a game. The game was made in two days during the weekend, since he had a job and it was the only free time we had. It was extremely fun to create a game that was so fast, so simple, and that managed to convey a feeling using only the bare minimum. I learned a lot about dealing with perfectionism and creating prototypes quickly.",
    "Nesse projeto, aprendi a me comunicar melhor com meu colega de equipe, entender que às vezes é mais importante deixar o ego de lado e encontrar uma ideia em comum. Compreendi que em um projeto em equipe é fundamental valorizar a opinião e a vontade de todos, e somente a partir daí criar um plano. Aprendi a aceitar os erros dos outros e reconhecer os meus próprios, buscando sempre melhorá-los. Essas habilidades de comunicação e colaboração são extremamente importantes em qualquer ambiente de trabalho, especialmente na área de tecnologia.": "In this project, I learned to communicate better with my teammate, understand that sometimes it's more important to put my ego aside and find a common idea. I understood that in a team project it is essential to value everyone's opinion and will, and only then create a plan. I learned to accept the mistakes of others and recognize my own, always seeking to improve them. These communication and collaboration skills are extremely important in any work environment, especially in technology.",
    "No meu último projeto com Unity, infelizmente não consegui finalizá-lo por diversas razões, incluindo minha ambição de criar um projeto maior do que o tempo que eu tinha disponível, falta de planejamento prévio ao desenvolvimento e problemas financeiros. No entanto, mesmo que inacabado, ainda considero importante mencioná-lo.": "On my last project with Unity, I unfortunately couldn't finish it for several reasons, including my ambition to create a project bigger than the time I had available, lack of pre-development planning and financial problems. However, even if unfinished, I still consider it important to mention it.",
    "Dediquei semanas ao desenvolvimento da lógica básica do jogo, background e escalabilidade. Durante esse processo, aprendi a importante lição de que a otimização precoce pode ser uma armadilha e um obstáculo para a criatividade. Meu projeto era um jogo de cartas altamente inspirado em jogos como Legends of Runeterra, Magic e Yugioh, mas acabou sendo mais ambicioso do que eu podia gerenciar na época.": "I spent weeks developing the basic game logic, background and scalability. During this process, I learned the important lesson that early optimization can be a pitfall and an obstacle to creativity. My project was a card game heavily inspired by games like Legends of Runeterra, Magic and Yugioh, but it turned out to be more ambitious than I could manage at the time.",
    "Com esse projeto, aprendi que não se pode substituir um pré-planejamento adequado e que é importante saber abandonar projetos que demandem muito tempo e energia para investir em outros mais simples. Também entendi a importância de lidar melhor com meus recursos e aceitar meus erros para crescer como programador.": "With this project, I learned that adequate pre-planning cannot be substituted and that it is important to know how to abandon projects that demand a lot of time and energy to invest it in simpler ones. I also understood the importance of handling my resources better and accepting my mistakes to grow as a programmer.",

    "Após isso, meu dinheiro estava começando a acabar e eu não sabia o que fazer. Não me parecia que desenvolvimento de jogos iria me levar para muito longe, então optei por trocar de área, e fui para ilustração digital.": "After that, my money was starting to run out and I didn't know what to do. It didn't seem to me that game development would take me very far, so I opted to change areas, and went to digital illustration.",
    "Aqui eu aprendi muito sobre como usar cores e shapes para compor uma experiencia artística. Entendi a valorizar a experiencia tanto de quem consome quanto a de quem desenvolve, e a partir dai julgar qual sentimento e ideia será enfatizado. Aprendi conceitos que hoje percebo o quão importante são para UX e UI.": "Here I learned a lot about how to use colors and shapes to compose an artistic experience. I understood to value the experience of both those who consume and those who develop, and from there judge which feeling and idea will be emphasized. I learned concepts that today I realize how important they are for UX and UI.",
    "Ainda indeciso, depois de explorar diversas áreas, decidi me dedicar ao desenvolvimento web e comecei a aprender as tecnologias básicas de front-end e back-end, como HTML, CSS, JavaScript, React, Node.js, Express, serviços em nuvem e muito mais. Uma das principais fontes de aprendizado foi o FreeCodeCamp, onde completei muitos projetos e exercícios, e assisti a muitas aulas. Entre eles, destaco o site do jogo da velha que criei para testar minhas habilidades.": "Still undecided, after exploring several areas, I decided to dedicate myself to web development and started to learn the basic front-end and back-end technologies, such as HTML, CSS, JavaScript, React, Node.js, Express, cloud services and a lot more. One of the main sources of learning was FreeCodeCamp, where I completed many projects and exercises, and watched many youtube classes. Among them, I highlight the tic-tac-toe website I created to test my skills.",
    "Durante esse projeto, pude perceber como os conceitos de ciência da computação e artes que havia aprendido anteriormente podiam ser facilmente transportados para outros projetos. Apesar de ter experiência com outros tipos de aplicativos e linguagens, consegui aplicar muitos dos conhecimentos que adquiri no desenvolvimento do jogo da velha. Isso me mostrou que, na teoria, todas as linguagens de programação seguem certos padrões e, ao aprender os fundamentos, é possível adaptar esse conhecimento facilmente a outros projetos, mesmo que a princípio pareçam completamente diferentes.": "During this project, I was able to see how the computer science and arts concepts I had learned earlier could be easily carried over to other projects. Despite having experience with other types of applications and languages, I was able to apply much of the knowledge I acquired in the tic-tac-toe website development. This showed me that, in theory, all programming languages follow certain patterns, and by learning the fundamentals, you can easily adapt that knowledge to other projects, even if they look completely different at first.",

    "Enquanto continuava indeciso em relação a minha carreira, escolhi investir em um curso de marketing com um dos maiores nomes de marketing digital de conteúdo do Brasil e do mundo, Paulo Cuenca. Por causa do curso ter atrasado o certificado, acabei reembolsando-o após 6 meses e, portanto, só tive acesso às aulas. No entanto, elas foram extremamente valiosas e me permitiram aprender várias coisas importantes sobre o mercado e como apresentar um produto.": "While I was still undecided about my career, I chose to invest in a marketing course with one of the biggest names in digital content marketing in Brazil and the world, Paulo Cuenca. Because of the course delaying the certificate, I ended up refunding it after 6 months and therefore only had access to the classes. However, they were extremely valuable and allowed me to learn a lot of important things about the market and how to present a product.",
    "Todas as aulas assistidas.": "All classes attended.",
    "O curso foi revelador e esclarecedor, mostrando como ainda temos comportamentos primitivos em um mundo digital e como é possível prever certos comportamentos para engajar produtos e ser melhor aceito. Além disso, o curso oferece reflexões sobre como ser você mesmo, aceitar ser parte de um nicho e criar conteúdo de qualidade para esse nicho, mesmo que você seja rejeitado por todos os outros. Acredito que tudo o que aprendi aqui é extremamente importante para entrar no mercado de trabalho empresarial.": "The course was revealing and enlightening, showing how we still have primitive behaviors in a digital world and how it is possible to predict certain behaviors to engage products and be better accepted. In addition, the course offers reflections on how to be yourself, accept being part of a niche and create quality content for that niche, even if you are rejected by everyone else. I believe that everything I learned here is extremely important to enter the job market.",
    "Acredito que o conhecimento adquirido no curso pode ser extremamente valioso para minha carreira como desenvolvedor de software. Compreender as necessidades e comportamentos dos usuários pode me ajudar a criar produtos mais eficientes e atraentes, além de me permitir trabalhar de forma mais próxima com as equipes de marketing e design.": "I believe that the knowledge acquired in the course can be extremely valuable for my career as a software developer. Understanding users' needs and behaviors can help me create more efficient and engaging products, as well as allow me to work more closely with the marketing and design teams.",

    "No final, tive que tomar uma decisão definitiva sobre qual área me dedicaria completamente, seguindo minhas paixões, e a escolha foi ciência da computação. É uma das minhas maiores paixões e uma das áreas de maior crescimento no mundo, com trabalhos bem remunerados. A partir daí, comecei a ler vários livros e a fazer o curso CS50 de Harvard, o qual esse site será usado como projeto final para receber meu certificado.": "In the end, I had to make a definitive decision about which area I would dedicate myself completely to, following my passions, and the choice was computer science. It's one of my biggest passions and one of the fastest growing areas in the world, with well paid jobs. From there, I started reading several books and taking the Harvard CS50 course, which this site will be used as a final project to earn my certificate.",
    "Li vários livros como \"Code Clean, Robert C. Martin\" e \"Game Programming Patterns, Robert Nystrom\".": "I read several books like \"Code Clean, Robert C. Martin\" and \"Game Programming Patterns, Robert Nystrom\".",
    "Com o livro Clean Code, aprendi a escrever códigos melhores, para que possam ser compreendidos por mim mesmo no futuro e pelos colegas de trabalho. O livro propõe muitas teorias interessantes sobre organização, embora haja algumas críticas de que aplicar essas teorias pode deixar o aplicativo até 20 vezes mais lento. No entanto, quando um código não precisa ser otimizado ao máximo, como em um robô que será enviado para Marte com pouca memória RAM e disco, aplicar esses conceitos é mais do que um bom hábito para criar códigos escaláveis e fáceis de manter.": "With the Clean Code book, I learned how to write better code, so that it can be understood by myself in the future and by co-workers. The book proposes many interesting theories about organization, although there is some criticism that applying these theories can slow down the application up to 20 times. However, when code doesn't need to be optimized to the maximum, as in a robot that will be sent to Mars with little RAM and disk, applying these concepts is more than a good habit to create scalable and maintainable code.",
    "Com o livro Game Programming Patterns, fui introduzido a muitas lógicas de organização, mas dessa vez, em vez de focar na leitura do código, a organização foca muito mais na lógica e no objetivo de escalar e estruturar grandes quantidades de lógica e códigos. O livro resume muitos conceitos do famoso livro Design Patterns dos GOF, adapta e foca naqueles mais usados em lógicas para jogos, que são conhecimentos muito procurados mesmo em áreas fora do desenvolvimento de jogos.": "With the book Game Programming Patterns, I was introduced to a lot of organization logic, but this time, instead of focusing on reading code, organization focuses much more on logic and the goal of scaling and structuring large amounts of logic and code. The book summarizes many concepts from the famous book Design Patterns by the GOF, adapts and focuses on those most used in game logic, which are knowledges in great demand even in areas outside of game development.",
    "Quanto aos livros que ainda pretendo terminar de ler, já que não tive tempo de concluir eles, incluem \"Computer Systems: A Programmer's Perspective, Randal Bryant\" e \"Operating System Concepts, Avi Silberschatz\".": "As for the books I still intend to finish reading, since I didn't have time to finish them, include \"Computer Systems: A Programmer's Perspective, Randal Bryant\" and \"Operating System Concepts, Avi Silberschatz\".",
    "Esses são, de longe, os livros mais importantes da minha carreira. Entender como os computadores funcionam em um nível mais baixo é fundamental em uma área em que surgem tantas vulnerabilidades com frequência. Com esses livros, tenho aprendido como a RAM, as redes, o disco rígido, a CPU e outros componentes funcionam e como podemos usar esse conhecimento para escrever códigos melhores, mais seguros e mais rápidos": "These are by far the most important books of my career. Understanding how computers work at a lower level is critical in an area where so many vulnerabilities frequently arise. From these books I have been learning how RAM, networks, hard disk, CPU and other components work and how we can use this knowledge to write better, safer and faster code.",
    "Nesse momento, estou buscando oportunidades de emprego enquanto finalizo meus estudos em ciência da computação. Apesar de estar passando por uma situação financeira complicada, estou focado em concluir este portfolio, obter meu certificado do curso CS50 de Harvard e começar a aplicar para vagas de emprego.": "Right now I am looking for job opportunities while I finish my studies in computer science. Despite being in a tough financial situation, I am focused on completing this portfolio, earning my CS50 certificate from Harvard and starting to apply for jobs.",

    "Após a conclusão deste projeto, pretendo continuar desenvolvendo minhas habilidades por meio de leituras e projetos pessoais, com planos de incorporar tecnologias como cloud, node e express em um site dinâmico como próximo desafio.": "Upon completion of this project, I intend to continue developing my skills through reading and personal projects, with plans to incorporate technologies such as cloud, node and express into a dynamic website as my next challenge.",
    "Acredito que este portfolio e minha trajetória de vida possam chamar a atenção de potenciais empregadores e me conceder oportunidades para entrevistas e, assim, eventualmente conquistar uma posição no mercado de trabalho. Estou ansioso para aplicar meu conhecimento e habilidades em um ambiente profissional e continuar crescendo na minha carreira.": "I believe that this portfolio and my life trajectory can attract the attention of potential employers and give me opportunities for interviews and, thus, eventually gain a position in the job market. I look forward to applying my knowledge and skills in a professional environment and continuing to grow in my career.",

    "Acredito que tenho algumas qualidades que podem me destacar no mercado, tais como minha paixão por aprender e compreender a ciência da computação, chegando ao ponto de estudar livros complexos sobre hardware e até mesmo fazer um curso rápido de engenharia elétrica para entender circuitos. Além disso, sou bastante comprometido e disciplinado com meus projetos, sempre buscando aprimorar minhas habilidades e conhecimentos para entregar um trabalho de qualidade.": "I believe I have some qualities that can set me apart in the market, such as my passion for learning and understanding computer science, going so far as to study complex hardware books and even take a crash course in electrical engineering to understand circuits. In addition, I am very committed and disciplined with my projects, always seeking to improve my skills and knowledge to deliver quality work.",
    "Busco constantemente me atualizar sobre as mais recentes tecnologias e tendências em desenvolvimento web, a fim de aprimorar minhas habilidades.": "I constantly seek to update myself on the latest technologies and trends in web development in order to improve my skills.",
    "Minha experiência anterior em artes, jogos e marketing, combinada com minhas habilidades em desenvolvimento web, me tornam um profissional altamente versátil e criativo, capaz de contribuir significativamente para o sucesso de projetos digitais em múltiplas áreas me permitindo trabalhar de forma mais próxima com as equipes de marketing e design.": "My previous experience in arts, games and marketing, combined with my skills in web development, make me a highly versatile and creative professional, capable of significantly contributing to the success of digital projects in multiple areas allowing me to work more closely with teams. of marketing and design.",
    "Possuo conhecimentos sólidos e aspiro sempre melhorar em ciências da computação, como hábitos de código limpo, sistemas operacionais, cloud, web, design, arquitetura de código, SOLID princípios, entre outros.": "I have solid knowledge and always aspire to improve in computer science, such as clean code habits, operating systems, cloud, web, design, code architecture, SOLID principles, among others.",
    "Altamente interessado na área, com extrema curiosidades em hardware, computer networking e cloud services.": "Highly interested in the area, with extreme curiosities in hardware, computer networking and cloud services.",
    "Tenho interesse em como a mente humana funciona e como criar experiências agradáveis em produtos com UX, UI e marketing.": "I am interested in how the human mind works and how to create enjoyable product experiences with UX, UI and marketing.",
    "Possuo conhecimentos sobre filosofia, o que se mostra necessário em tempos difíceis para uma reflexão mais profunda sobre política, saúde humana, psicologia, sentido da vida e outros temas relevantes.": "I have knowledge of philosophy, which is necessary in difficult times for a deeper reflection on politics, human health, psychology, the meaning of life and other relevant topics.",
    "Como a média de leitura no país é de 2,43 livros por ano, meus hábitos de leitura sobre filosofia e ciências da computação são um grande diferencial.": "As the average reading in Brazil is 2.43 books per year, my reading habits on philosophy and computer science is a big differential.",
    "Tenho vasta experiência trabalhando em equipe e criando jogos para game jams, o que aprimorou minhas habilidades de comunicação e sociais.": "I have extensive experience working in teams and creating games for game jams, which has improved my communication and social skills.",

    
    "silencepleaseofficialbr@gmail.com" : "silencepleaseofficialbr@gmail.com"
}
let isEnglish = false;

const arr = document.querySelectorAll("p, header, .point, a:not(.icon)");
const language_switch = document.getElementById("language-switch");
const en_us = language_switch.firstElementChild;
const pt_br = language_switch.lastElementChild;
// changeLanguage();

en_us.addEventListener("click", () => {
    if (isEnglish) return;
    changeLanguage();
});

pt_br.addEventListener("click", () => {
    if (!isEnglish) return;
    changeLanguage();
})

document.addEventListener("keydown", function (event) {
    if (event.key === "e") {
        changeLanguage();
    }
});

function changeLanguage() {
    if (!isEnglish) {
        arr.forEach(el => {
            el.textContent = dictionary[el.textContent.replace(/\s+/g, ' ').trim()];
        });
    }
    else {
        arr.forEach(el => {
            el.textContent = getKeyByValue(el.textContent.replace(/\s+/g, ' ').trim());
        });
    }

    isEnglish = !isEnglish;
    updateLanguageButtons();
}

function getKeyByValue(value) {
    return Object.keys(dictionary).find(key => dictionary[key] === value);
};


function updateLanguageButtons() {
    if (isEnglish) {
        pt_br.classList.remove("active");
        en_us.classList.add("active");
        return;
    }
    pt_br.classList.add("active");
    en_us.classList.remove("active");
};